/**
 * Job Description Analyzer Service
 *
 * Analyzes job descriptions to extract:
 * - Required skills and technologies
 * - Experience level (entry/mid/senior)
 * - Key responsibilities
 * - Soft skills and personality traits
 * - Company culture indicators
 *
 * Used to generate targeted, job-specific questions for conversational resume building.
 */

class JobDescriptionAnalyzer {
  constructor(geminiService) {
    this.gemini = geminiService;
  }

  /**
   * Main analysis method
   * @param {string} jobDescription - Raw job description text
   * @param {string} existingResume - Optional: Candidate's existing resume for gap analysis
   * @returns {Promise<Object>} Analyzed JD data with Gemini-generated questions
   */
  async analyze(jobDescription, existingResume = null) {
    if (!jobDescription || jobDescription.trim().length < 50) {
      throw new Error('Job description is too short (minimum 50 characters)');
    }

    // Use Gemini to deeply analyze the JD AND generate custom questions
    // If existingResume is provided, perform gap analysis
    const aiResponse = await this.analyzeWithAI(jobDescription, existingResume);

    // aiResponse now contains: { analysis: {...}, questions: [...] }
    // Questions are generated by Gemini based on the specific JD, not templates!
    // If resume provided, questions target gaps only (2-5 questions instead of always 5)

    return {
      jobDescription,
      existingResume: existingResume ? 'provided' : 'none', // Don't store full resume in response
      analysis: aiResponse.analysis || aiResponse, // Handle both old and new format
      questions: aiResponse.questions || this.generateQuestions(aiResponse), // Fallback to templates if needed
      analyzedAt: new Date().toISOString(),
      generatedBy: aiResponse.questions ? 'gemini' : 'template',
      hasResume: !!existingResume
    };
  }

  /**
   * Use Gemini AI to analyze job description (with optional resume gap analysis)
   */
  async analyzeWithAI(jobDescription, existingResume = null) {
    // Enhanced prompt that handles both scenarios:
    // 1. No resume: Ask 5 comprehensive questions
    // 2. Has resume: Analyze gaps, ask 2-5 targeted questions only

    const resumeContext = existingResume ? `

**CANDIDATE'S EXISTING RESUME:**
${existingResume}

**CRITICAL: RESUME-FIRST MODE**
The candidate already has resume content. Your job is to:
1. Identify what they ALREADY documented well
2. Find GAPS where they're missing skills/experience the JD requires
3. Find WEAK sections that exist but lack metrics/specifics
4. Ask ONLY 2-5 questions to fill these gaps (NOT about what they already covered)

This prevents redundant questions and makes the process faster (5-8 min vs 10-15 min).` : `

**NO EXISTING RESUME PROVIDED**
Ask 5 comprehensive questions to build their resume from scratch.`;

    const prompt = `You are an expert career coach helping build a personalized resume through conversational AI.

**CONTEXT & GOAL:**
I'm helping a candidate apply for a specific job.${resumeContext}

**JOB DESCRIPTION:**
${jobDescription}

**YOUR TASK:**
Analyze this JD deeply and return structured data + custom questions (2-5 if resume provided, 5 if not).

**RESPOND IN THIS EXACT JSON FORMAT:**

{
  "analysis": {
    "jobTitle": "Exact title from the posting",
    "company": "Company name or 'Not specified'",
    "industry": "e.g., Technology, Healthcare, Construction, Retail, Hospitality",
    "roleType": "technical|non-technical|hybrid",
    "experienceLevel": "entry|mid|senior|executive",
    "requiredSkills": {
      "core": ["The 3-5 MOST critical skills for this specific role - be precise!"],
      "technical": ["Hard skills, tools, technologies - ONLY if mentioned in JD"],
      "soft": ["Soft skills they explicitly want"],
      "physical": ["Physical requirements like 'lifting 50lbs', 'standing for 8 hours' - ONLY if mentioned"]
    },
    "keyResponsibilities": [
      "Top 3-5 actual responsibilities from the JD (use their exact language)"
    ],
    "workEnvironment": {
      "setting": "office|remote|warehouse|construction site|retail|field work|etc",
      "pace": "fast-paced|steady|project-based",
      "teamSize": "solo|small team|large team|cross-functional",
      "schedule": "standard hours|shifts|flexible|on-call"
    },
    "culturalIndicators": {
      "values": ["What does the company seem to value based on language used?"],
      "workStyle": "independent|collaborative|hybrid",
      "traits": ["Personality traits they're seeking - infer from their word choices"]
    },
    "compensationInfo": {
      "salaryRange": "If disclosed, otherwise 'Not disclosed'",
      "benefits": ["Any mentioned benefits"]
    },
    "atsKeywords": [
      "Top 10-15 keywords that MUST appear in resume for ATS matching"
    ],
    "resumeGapAnalysis": {
      "strengths": ["What resume already demonstrates well - ONLY if resume provided, else empty array"],
      "weaknesses": ["Sections lacking depth/metrics - ONLY if resume provided, else empty array"],
      "missingContent": ["Required skills completely absent - ONLY if resume provided, else empty array"],
      "atsMatchScore": 0,
      "questionCount": 5
    }
  },
  "questions": [
    {
      "id": "jd_question_1",
      "category": "experience|achievement|behavioral|technical|situational",
      "question": "YOUR CUSTOM QUESTION HERE - Make it specific to THIS job!",
      "purpose": "Why you're asking this - what resume content you're trying to extract",
      "gapType": "missing|weak|unquantified|comprehensive",
      "expectedAnswerElements": [
        "What you hope to learn from their answer (for resume writing)"
      ],
      "followUp": "A natural follow-up question if they give a vague answer"
    }
    // ... More questions: 2-5 if resume provided (based on gaps), always 5 if no resume
  ]
}

**CRITICAL INSTRUCTIONS FOR QUESTION GENERATION:**

FOR TECHNICAL ROLES (Software, Engineering, IT):
- Ask about specific technologies/tools mentioned in the JD
- Request quantifiable achievements (performance improvements, bugs fixed, systems built)
- Focus on problem-solving and technical depth

FOR NON-TECHNICAL ROLES (General Labor, Retail, Hospitality, Construction):
- Ask about physical tasks, safety, teamwork, reliability
- Focus on work ethic, following procedures, customer service
- Request examples of handling difficult situations or busy periods
- DO NOT ask about AWS, APIs, or programming unless explicitly in the JD!

FOR ALL ROLES:
- Question 1: Should target their CORE skill/responsibility from the JD
- Question 2: Should probe for a specific achievement/challenge they've overcome
- Question 3: Should validate a soft skill the employer wants
- Question 4: Should assess cultural/work environment fit
- Question 5: Should explore their motivation and understanding of the role

**IMPORTANT:**
- Use the EXACT language from the job description when possible
- If it's a General Laborer role, ask about "lifting", "warehouse work", "team coordination"
- If it's a Software Engineer role, ask about their tech stack, architecture decisions, code quality
- Make questions conversational but specific
- Each question should help write 2-3 bullet points on their resume

**EXAMPLES:**

Bad (Generic): "Tell me about a time you worked on a team."
Good (Specific to JD): "This role involves working in a fast-paced warehouse environment. Tell me about a time you had to coordinate with a team to meet a tight shipping deadline. What was your specific role?"

Bad (Wrong tech): "Tell me about your experience with AWS and REST APIs." (when JD is for construction)
Good (JD-specific): "You'll be operating heavy machinery on construction sites. Walk me through your experience with equipment like forklifts or pallet jacks. What safety protocols do you follow?"

Respond ONLY with valid JSON (no markdown, no code blocks).`;

    try {
      const model = this.gemini.getFlashModel(); // Fast model for analysis
      const result = await model.generateContent(prompt);
      const response = result.response;

      // Vertex AI response format: response.candidates[0].content.parts[0].text
      let responseText;
      if (typeof response.text === 'function') {
        // Old format
        responseText = response.text();
      } else if (response.candidates && response.candidates[0]) {
        // Vertex AI format
        responseText = response.candidates[0].content.parts[0].text;
      } else {
        throw new Error('Unexpected response format from Gemini');
      }

      console.log('🤖 Gemini raw response (first 200 chars):', responseText.substring(0, 200));

      // Parse JSON response
      let cleanedResponse = responseText.trim();
      // Remove markdown code blocks if present
      cleanedResponse = cleanedResponse.replace(/```json\n?/g, '').replace(/```\n?/g, '');

      const parsedResponse = JSON.parse(cleanedResponse);

      // NEW FORMAT: Gemini returns { analysis: {...}, questions: [...] }
      // Validate required fields
      // Questions can be 2-5 (gap-filling) or 5 (comprehensive)
      if (!parsedResponse.analysis || !parsedResponse.questions ||
          parsedResponse.questions.length < 2 || parsedResponse.questions.length > 5) {
        console.warn('⚠️  AI response missing required fields or invalid question count, using fallback');
        throw new Error('AI response missing required fields or wrong format');
      }

      const questionCount = parsedResponse.questions.length;
      const hasGapAnalysis = parsedResponse.analysis.resumeGapAnalysis &&
                             parsedResponse.analysis.resumeGapAnalysis.strengths.length > 0;

      console.log('✅ Gemini generated', questionCount, 'custom questions',
                  hasGapAnalysis ? '(gap-filling mode)' : '(comprehensive mode)');
      return parsedResponse;

    } catch (error) {
      console.error('AI analysis failed:', error);
      console.error('Error details:', error.message);

      // Fallback: Basic keyword extraction
      console.log('⚠️  Using fallback analysis (regex-based)');
      return this.fallbackAnalysis(jobDescription);
    }
  }

  /**
   * Fallback analysis if AI fails (regex-based)
   */
  fallbackAnalysis(jobDescription) {
    const text = jobDescription.toLowerCase();

    // Detect experience level
    let experienceLevel = 'mid';
    if (text.includes('entry') || text.includes('junior') || text.includes('0-2 years')) {
      experienceLevel = 'entry';
    } else if (text.includes('senior') || text.includes('lead') || text.includes('5+ years')) {
      experienceLevel = 'senior';
    } else if (text.includes('director') || text.includes('vp') || text.includes('executive')) {
      experienceLevel = 'executive';
    }

    // Extract technical skills (common technologies)
    const techKeywords = [
      'javascript', 'python', 'java', 'react', 'node', 'sql', 'aws', 'docker',
      'kubernetes', 'git', 'api', 'rest', 'graphql', 'typescript', 'html', 'css',
      'mongodb', 'postgresql', 'redis', 'linux', 'ci/cd', 'agile', 'scrum'
    ];
    const technical = techKeywords.filter(skill => text.includes(skill));

    // Extract soft skills
    const softSkillKeywords = [
      'communication', 'leadership', 'teamwork', 'problem-solving', 'analytical',
      'detail-oriented', 'self-motivated', 'collaborative', 'creative', 'adaptable'
    ];
    const soft = softSkillKeywords.filter(skill => text.includes(skill));

    // Detect remote/hybrid
    const isRemote = text.includes('remote') || text.includes('work from home');
    const isHybrid = text.includes('hybrid');

    return {
      jobTitle: 'Position (extracted from JD)',
      company: 'Not specified',
      experienceLevel,
      requiredSkills: {
        technical: technical.length > 0 ? technical : ['Not specified'],
        soft: soft.length > 0 ? soft : ['Communication', 'Problem-solving'],
        certifications: []
      },
      keyResponsibilities: [
        'Extracted from job description (AI analysis unavailable)'
      ],
      culturalIndicators: {
        workStyle: 'collaborative',
        pace: 'steady',
        innovation: 'medium'
      },
      educationRequired: 'Not specified',
      locationInfo: {
        location: 'Not specified',
        isRemote,
        isHybrid
      },
      salaryRange: {
        min: 0,
        max: 0,
        currency: 'USD',
        disclosed: false
      },
      topKeywords: [...technical, ...soft].slice(0, 10),
      personalityTraits: soft,
      fallbackUsed: true
    };
  }

  /**
   * Generate 5 JD-specific questions based on analysis
   */
  generateQuestions(analysis) {
    const questions = [];

    // Question 1: Technical skills (if technical role)
    if (analysis.requiredSkills.technical.length > 0) {
      const topTechs = analysis.requiredSkills.technical.slice(0, 3).join(', ');
      questions.push({
        id: 'jd_technical',
        type: 'experience',
        question: `This role requires experience with ${topTechs}. Tell me about a project where you used these technologies to solve a challenging problem. What was the outcome?`,
        purpose: 'technical_validation',
        keywords: analysis.requiredSkills.technical,
        followUp: 'What specific results or metrics came from this project?'
      });
    } else {
      questions.push({
        id: 'jd_experience',
        type: 'experience',
        question: `Tell me about your most relevant professional experience that relates to this ${analysis.jobTitle} position. What were your key accomplishments?`,
        purpose: 'experience_validation',
        keywords: analysis.topKeywords,
        followUp: 'Can you quantify the impact you made?'
      });
    }

    // Question 2: Key responsibility
    if (analysis.keyResponsibilities.length > 0) {
      const topResponsibility = analysis.keyResponsibilities[0];
      questions.push({
        id: 'jd_responsibility',
        type: 'achievement',
        question: `A key responsibility in this role is: "${topResponsibility}". Describe a time when you successfully handled a similar responsibility. What was your approach?`,
        purpose: 'responsibility_match',
        keywords: analysis.topKeywords,
        followUp: 'What obstacles did you overcome, and what was the result?'
      });
    }

    // Question 3: Soft skill match
    const topSoftSkill = analysis.requiredSkills.soft[0] || 'problem-solving';
    questions.push({
      id: 'jd_soft_skill',
      type: 'behavioral',
      question: `This position requires strong ${topSoftSkill} skills. Share an example that demonstrates your ${topSoftSkill} abilities in a professional setting.`,
      purpose: 'soft_skill_validation',
      keywords: analysis.requiredSkills.soft,
      followUp: 'How did your team or organization benefit from your approach?'
    });

    // Question 4: Experience level match
    const experienceQuestion = this.getExperienceLevelQuestion(analysis.experienceLevel, analysis.jobTitle);
    questions.push(experienceQuestion);

    // Question 5: Cultural fit / personality
    const cultureQuestion = this.getCultureFitQuestion(analysis.culturalIndicators, analysis.personalityTraits);
    questions.push(cultureQuestion);

    return questions;
  }

  /**
   * Generate experience-level specific question
   */
  getExperienceLevelQuestion(level, jobTitle) {
    const questions = {
      entry: {
        id: 'jd_entry_growth',
        type: 'growth',
        question: `As you're starting your career as a ${jobTitle}, what academic projects, internships, or personal initiatives have prepared you for this role? What did you learn?`,
        purpose: 'entry_validation',
        followUp: 'How do you plan to apply this learning to the role?'
      },
      mid: {
        id: 'jd_mid_impact',
        type: 'impact',
        question: `With your experience level, you'll be expected to deliver results independently. Tell me about a time you owned a project from start to finish. What was the impact?`,
        purpose: 'mid_validation',
        followUp: 'What would you do differently if you could do it again?'
      },
      senior: {
        id: 'jd_senior_leadership',
        type: 'leadership',
        question: `Senior ${jobTitle} roles require both technical excellence and leadership. Describe a situation where you mentored others or led a strategic initiative. What was the outcome?`,
        purpose: 'senior_validation',
        followUp: 'How did you measure success, and what did your team learn?'
      },
      executive: {
        id: 'jd_exec_vision',
        type: 'strategic',
        question: `Executive-level ${jobTitle} positions require strategic vision and organizational impact. Share an example of how you've driven company-wide change or built something from the ground up.`,
        purpose: 'executive_validation',
        followUp: 'What was the business impact, and how did you get stakeholder buy-in?'
      }
    };

    return questions[level] || questions.mid;
  }

  /**
   * Generate culture-fit question based on company indicators
   */
  getCultureFitQuestion(cultural, traits) {
    const { workStyle, pace, innovation } = cultural;

    let question = '';
    let purpose = 'culture_fit';

    if (pace === 'fast-paced' && innovation === 'high') {
      question = `This company values innovation and moves quickly. Tell me about a time you had to learn something new rapidly or pivot on a project with changing requirements. How did you adapt?`;
      purpose = 'adaptability_innovation';
    } else if (workStyle === 'collaborative') {
      question = `Collaboration is key in this role. Describe a situation where you worked with a cross-functional team to achieve a goal. What was your specific contribution?`;
      purpose = 'teamwork_collaboration';
    } else if (traits.includes('detail-oriented') || traits.includes('analytical')) {
      question = `This role requires meticulous attention to detail. Share an example where your careful analysis or thoroughness prevented a problem or improved an outcome.`;
      purpose = 'detail_orientation';
    } else {
      question = `Every company has a unique culture. What type of work environment brings out your best work, and why do you think you'd thrive in this ${workStyle} setting?`;
      purpose = 'work_preference';
    }

    return {
      id: 'jd_culture_fit',
      type: 'culture',
      question,
      purpose,
      keywords: traits,
      followUp: 'What did you learn about yourself from that experience?'
    };
  }

  /**
   * Quick validation of job description quality
   */
  validateJobDescription(jobDescription) {
    const text = jobDescription.trim();

    if (text.length < 50) {
      return { valid: false, reason: 'Job description is too short (minimum 50 characters)' };
    }

    if (text.length > 20000) {
      return { valid: false, reason: 'Job description is too long (maximum 20,000 characters)' };
    }

    // Check if it looks like a real JD (has at least some job-related keywords)
    const jobKeywords = [
      'experience', 'skills', 'responsibilities', 'requirements', 'qualifications',
      'role', 'position', 'team', 'work', 'candidate', 'seeking', 'looking for'
    ];

    const lowerText = text.toLowerCase();
    const hasKeywords = jobKeywords.some(keyword => lowerText.includes(keyword));

    if (!hasKeywords) {
      return {
        valid: false,
        reason: 'This doesn\'t appear to be a job description. Please paste the full job posting.'
      };
    }

    return { valid: true };
  }
}

module.exports = JobDescriptionAnalyzer;
