-- Add missing personality traits fields
-- These fields are generated by Gemini AI but weren't in original schema

ALTER TABLE personality_traits
ADD COLUMN IF NOT EXISTS leadership_style VARCHAR(255),
ADD COLUMN IF NOT EXISTS motivation_type VARCHAR(255),
ADD COLUMN IF NOT EXISTS decision_making VARCHAR(255),
ADD COLUMN IF NOT EXISTS inference_confidence DECIMAL(3,2),
ADD COLUMN IF NOT EXISTS analysis_version VARCHAR(50);

-- Verify columns were added
SELECT column_name, data_type
FROM information_schema.columns
WHERE table_name = 'personality_traits'
ORDER BY ordinal_position;
